"""add_generated_creatives_table

Revision ID: 047883543b83
Revises:
Create Date: 2025-11-10 16:54:12.751746

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "047883543b83"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "generated_creatives",
        sa.Column("creative_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("campaign_id", sa.Integer(), nullable=False),
        sa.Column("variant_number", sa.Integer(), nullable=False),
        sa.Column("channel_type", sa.String(length=50), nullable=False),
        sa.Column("image_filename", sa.Text(), nullable=False),
        sa.Column("image_url", sa.Text(), nullable=False),
        sa.Column("prompt_used", sa.Text(), nullable=False),
        sa.Column("generation_params", sa.Text(), nullable=False),
        sa.Column("model_used", sa.String(length=100), nullable=False),
        sa.Column("recommendation_score", sa.Integer(), nullable=False),
        sa.Column("score_reasoning", sa.Text(), nullable=True),
        sa.Column("is_selected", sa.Boolean(), nullable=False, default=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "variant_number >= 1 AND variant_number <= 3", name="check_variant_number_range"
        ),
        sa.CheckConstraint(
            "channel_type IN ('email_header', 'push_header')", name="check_channel_type_valid"
        ),
        sa.CheckConstraint(
            "recommendation_score >= 0 AND recommendation_score <= 100",
            name="check_recommendation_score_range",
        ),
        sa.ForeignKeyConstraint(["campaign_id"], ["campaigns.campaign_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("creative_id"),
    )
    op.create_index("idx_creative_campaign", "generated_creatives", ["campaign_id"], unique=False)
    op.create_index("idx_creative_created", "generated_creatives", ["created_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_creative_created", table_name="generated_creatives")
    op.drop_index("idx_creative_campaign", table_name="generated_creatives")
    op.drop_table("generated_creatives")
    # ### end Alembic commands ###
